# Generated by Django 5.2.17 on 2026-08-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=40)),
                ('video_file', models.FileField(upload_to='videos')),
                ('thumbnail', models.FileField(blank=True, upload_to='thumbnails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('category', ''), _negated=True), name='video_category_not_empty')],
            },
        ),
    ]
